using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImageApp.UnitTests.Lib.NewtonsoftJson
{
    public class AutogeneratedPropertyModel
    {
        public string Value { get; set; }
    }
}
